#!/usr/bin/perl

$window = shift @ARGV;
$interactive = shift @ARGV;

$username = `whoami`;
chomp $username;
$masterLog = "/home/student/jourmeob/.myTalk/masterLog.txt";

$LOGFILE = "/home/student/" . $username . "/.myTalk/log.txt";

system("tail -s 1 -f '$masterLog' >> '$LOGFILE' &");




if($window eq "nw")
{

   if($interactive eq "true")
   {
      my $childID = fork();
      
      if($childID == 0) #Child
      {
      
         exec("~/.myTalk/tailTalk '$LOGFILE' ");
      
      }
      else
      {
      
         return;
      
      }
      
   }
   else
   {
      system("~/.myTalk/tailTalk '$LOGFILE' &");
   }

}
elsif($window eq "local")
{
   system ("x-terminal-emulator -e ./tailTalk '$LOGFILE' &");
}
elsif($window eq "localnw")
{

   if($interactive eq "true")
   {
   
      my $childID = fork();
      
      if($childID == 0) #Child
      {
      
         exec("./tailTalk '$LOGFILE' ");
         
      }
      else
      {
         return;
      }
      
      
   }
   else
   {
      system("./tailTalk '$LOGFILE' &");
   }

}
else
{
   system("x-terminal-emulator -e ~/.myTalk/tailTalk '$LOGFILE' &");
}



